<?php

namespace Database\Seeders;

use App\Models\GoalKpi;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GoalKpiSeeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function () {
            GoalKpi::query()->delete();

            $data = [
                6 => [
                    [
                        'no' => 1,
                        'indikator_kinerja_perusahaan' => 'Revenue',
                        'indikator_kinerja_individu' => '1.Target penjualan',
                        'baseline_2025' => 2844526180.35,
                        'target_2026' => 13000000000,
                        'bobot_target' => 0.7,
                    ],
                    [
                        'no' => 2,
                        'indikator_kinerja_perusahaan' => 'Revenue',
                        'indikator_kinerja_individu' => '2. Tingkat konversi penjualan',
                        'baseline_2025' => 0.24,
                        'target_2026' => 0.8,
                        'bobot_target' => 0.02,
                    ],
                    [
                        'no' => 3,
                        'indikator_kinerja_perusahaan' => '# Pelanggan Baru',
                        'indikator_kinerja_individu' => '3. Jumlah pelanggan baru',
                        'baseline_2025' => 9,
                        'target_2026' => 6,
                        'bobot_target' => 0.016666666666666666,
                    ],
                    [
                        'no' => 4,
                        'indikator_kinerja_perusahaan' => 'Revenue',
                        'indikator_kinerja_individu' => '4. Nilai Kontrak',
                        'baseline_2025' => 2844526180.35,
                        'target_2026' => 13000000000,
                        'bobot_target' => 0.016666666666666666,
                    ],
                    [
                        'no' => 5,
                        'indikator_kinerja_perusahaan' => 'Revenue',
                        'indikator_kinerja_individu' => '5. Waktu penjualan',
                        'baseline_2025' => 0.2074,
                        'target_2026' => 1,
                        'bobot_target' => 0.016666666666666666,
                    ],
                    [
                        'no' => 6,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '6. Tingkat kepuasan pelanggan',
                        'baseline_2025' => 4,
                        'target_2026' => 4,
                        'bobot_target' => 0.016666666666666666,
                    ],
                    [
                        'no' => 7,
                        'indikator_kinerja_perusahaan' => 'Revenue',
                        'indikator_kinerja_individu' => '7. Retensi pelanggan',
                        'baseline_2025' => 0.565,
                        'target_2026' => 0.8,
                        'bobot_target' => 0.016666666666666666,
                    ],
                    [
                        'no' => 8,
                        'indikator_kinerja_perusahaan' => 'Product share',
                        'indikator_kinerja_individu' => '8. Product share',
                        'baseline_2025' => 4,
                        'target_2026' => 19,
                        'bobot_target' => 0.05,
                    ],
                    [
                        'no' => 9,
                        'indikator_kinerja_perusahaan' => 'Penyelesaian PO pelanggan',
                        'indikator_kinerja_individu' => '9. Tingkat penyelesaian PO pelanggan',
                        'baseline_2025' => 0.87,
                        'target_2026' => 1,
                        'bobot_target' => 0.08,
                    ],
                    [
                        'no' => 10,
                        'indikator_kinerja_perusahaan' => 'Implementasi ERP',
                        'indikator_kinerja_individu' => '10. Implementasi ERP',
                        'baseline_2025' => 0.5,
                        'target_2026' => 1,
                        'bobot_target' => 0.016666666666666666,
                    ],
                    [
                        'no' => 11,
                        'indikator_kinerja_perusahaan' => 'Skor Engagement Karyawan',
                        'indikator_kinerja_individu' => '11. Skor Engagement Karyawan',
                        'baseline_2025' => 3.3,
                        'target_2026' => 3,
                        'bobot_target' => 0.016666666666666666,
                    ],
                    [
                        'no' => 12,
                        'indikator_kinerja_perusahaan' => 'Rerata jam learning per orang',
                        'indikator_kinerja_individu' => '12. Rerata jam pelatihan per orang',
                        'baseline_2025' => 24,
                        'target_2026' => 48,
                        'bobot_target' => 0.016666666666666666,
                    ],
                    [
                        'no' => 13,
                        'indikator_kinerja_perusahaan' => '#temuan',
                        'indikator_kinerja_individu' => '13. Tidak ada temuan di audit internal terkait ISO',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => 0.016666666666666666,
                    ],
                ],
                7 => [
                    [
                        'no' => 1,
                        'indikator_kinerja_perusahaan' => 'Revenue',
                        'indikator_kinerja_individu' => '1.Target penjualan',
                        'baseline_2025' => 2768866043.36,
                        'target_2026' => 11000000000,
                        'bobot_target' => 0.7,
                    ],
                    [
                        'no' => 2,
                        'indikator_kinerja_perusahaan' => 'Revenue',
                        'indikator_kinerja_individu' => '2. Tingkat konversi penjualan',
                        'baseline_2025' => 0.17,
                        'target_2026' => 0.8,
                        'bobot_target' => 0.02,
                    ],
                    [
                        'no' => 3,
                        'indikator_kinerja_perusahaan' => '# Pelanggan Baru',
                        'indikator_kinerja_individu' => '3. Jumlah pelanggan baru',
                        'baseline_2025' => 2,
                        'target_2026' => 6,
                        'bobot_target' => 0.016666666666666666,
                    ],
                    [
                        'no' => 4,
                        'indikator_kinerja_perusahaan' => 'Revenue',
                        'indikator_kinerja_individu' => '4. Nilai Kontrak',
                        'baseline_2025' => 2768866043.36,
                        'target_2026' => 11000000000,
                        'bobot_target' => 0.016666666666666666,
                    ],
                    [
                        'no' => 5,
                        'indikator_kinerja_perusahaan' => 'Revenue',
                        'indikator_kinerja_individu' => '5. Waktu penjualan',
                        'baseline_2025' => 0.15,
                        'target_2026' => 1,
                        'bobot_target' => 0.016666666666666666,
                    ],
                    [
                        'no' => 6,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '6. Tingkat kepuasan pelanggan',
                        'baseline_2025' => 4,
                        'target_2026' => 4,
                        'bobot_target' => 0.016666666666666666,
                    ],
                    [
                        'no' => 7,
                        'indikator_kinerja_perusahaan' => 'Revenue',
                        'indikator_kinerja_individu' => '7. Retensi pelanggan',
                        'baseline_2025' => 0.55,
                        'target_2026' => 0.8,
                        'bobot_target' => 0.016666666666666666,
                    ],
                    [
                        'no' => 8,
                        'indikator_kinerja_perusahaan' => 'Product share',
                        'indikator_kinerja_individu' => '8. Product share',
                        'baseline_2025' => 5,
                        'target_2026' => 19,
                        'bobot_target' => 0.05,
                    ],
                    [
                        'no' => 9,
                        'indikator_kinerja_perusahaan' => 'Penyelesaian PO pelanggan',
                        'indikator_kinerja_individu' => '9. Tingkat penyelesaian PO pelanggan',
                        'baseline_2025' => 0.956,
                        'target_2026' => '100 %',
                        'bobot_target' => 0.08,
                    ],
                    [
                        'no' => 10,
                        'indikator_kinerja_perusahaan' => 'Implementasi ERP',
                        'indikator_kinerja_individu' => '10. Implementasi ERP',
                        'baseline_2025' => 0.8,
                        'target_2026' => 1,
                        'bobot_target' => 0.016666666666666666,
                    ],
                    [
                        'no' => 11,
                        'indikator_kinerja_perusahaan' => 'Skor Engagement Karyawan',
                        'indikator_kinerja_individu' => '11. Skor Engagement Karyawan',
                        'baseline_2025' => 3.9,
                        'target_2026' => 3,
                        'bobot_target' => 0.016666666666666666,
                    ],
                    [
                        'no' => 12,
                        'indikator_kinerja_perusahaan' => 'Rerata jam learning per orang',
                        'indikator_kinerja_individu' => '12. Rerata jam pelatihan per orang',
                        'baseline_2025' => 24,
                        'target_2026' => 48,
                        'bobot_target' => 0.016666666666666666,
                    ],
                    [
                        'no' => 13,
                        'indikator_kinerja_perusahaan' => '#temuan',
                        'indikator_kinerja_individu' => '13. Tidak ada temuan di audit internal terkait ISO',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => 0.016666666666666666,
                    ],
                ],
                8 => [
                    [
                        'no' => 1,
                        'indikator_kinerja_perusahaan' => 'Akurasi laporan keuangan',
                        'indikator_kinerja_individu' => '1. Tingkat Akurasi Pelaporan Keuangan: Persentase kesalahan pelaporan.',
                        'baseline_2025' => 0,
                        'target_2026' => 0,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 2,
                        'indikator_kinerja_perusahaan' => 'Akurasi laporan keuangan',
                        'indikator_kinerja_individu' => '2. Waktu Pelaporan Keuangan : Waktu antara tutup buku dan pelaporan',
                        'baseline_2025' => 'SPT Badan 2024 : 4 Bulan ( 2 Mei 2025 )',
                        'target_2026' => 'Maksimum 2 bulan',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 3,
                        'indikator_kinerja_perusahaan' => 'Ketepatan penagihan',
                        'indikator_kinerja_individu' => '3. Waktu Pengolahan Transaksi :Waktu pengolahan transaksi/penerbitan dokumen',
                        'baseline_2025' => 1,
                        'target_2026' => 'Same day',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 4,
                        'indikator_kinerja_perusahaan' => 'Ketepatan penagihan',
                        'indikator_kinerja_individu' => '4. Tingkat Akurasi Pengolahan Transaksi: Persentase kesalahan pengolahan',
                        'baseline_2025' => 0.06,
                        'target_2026' => 0,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 5,
                        'indikator_kinerja_perusahaan' => 'Revenue',
                        'indikator_kinerja_individu' => '5. Jumlah Transaksi yang Diproses : Jumlah transaksi per periode',
                        'baseline_2025' => 'Rp 76.858.935.169 
76,86%
Franco Rp. 22.492.003.086
TT/LC Rp. 54.366.932.083',
                        'target_2026' => 'Rp.100.000.000.000',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 6,
                        'indikator_kinerja_perusahaan' => 'Akurasi laporan keuangan',
                        'indikator_kinerja_individu' => '6. Waktu Respons terhadap Permintaan: Waktu respons terhadap permintaan',
                        'baseline_2025' => 'Same day',
                        'target_2026' => 'same day',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 7,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '7. Tingkat Kepuasan Pelanggan: Kepuasan pelanggan terhadap layanan. Tingkat Kepuasan Pelanggan: Kepuasan pelanggan terhadap layanan',
                        'baseline_2025' => '-',
                        'target_2026' => '4 skala 5',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 8,
                        'indikator_kinerja_perusahaan' => 'Akurasi laporan keuangan',
                        'indikator_kinerja_individu' => '8. Peningkatan Kualitas Pelaporan : Kualitas pelaporan keuangan',
                        'baseline_2025' => 'Masih dalam Proses - 60%',
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 9,
                        'indikator_kinerja_perusahaan' => 'Ketepatan penagihan',
                        'indikator_kinerja_individu' => '9. Piutang tidak tertagih',
                        'baseline_2025' => '2024 : Rp. 179.940.825
CV Jaya Lestari Rp. 21.950.825
PT. SAI Rp. 157.990.000',
                        'target_2026' => '1% dari revenue',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 10,
                        'indikator_kinerja_perusahaan' => 'Implementasi ERP',
                        'indikator_kinerja_individu' => '10. Implementasi ERP',
                        'baseline_2025' => 0.8,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 11,
                        'indikator_kinerja_perusahaan' => 'Skor engagement karyawan',
                        'indikator_kinerja_individu' => '11. Skor engagement karyawan',
                        'baseline_2025' => 3.9,
                        'target_2026' => '3 skala 5',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 12,
                        'indikator_kinerja_perusahaan' => 'Rerata jam learning per orang',
                        'indikator_kinerja_individu' => '12. Rerata jam pelatihan per orang',
                        'baseline_2025' => 24,
                        'target_2026' => '4 jam/bulan/orang ( Total 48 )',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 13,
                        'indikator_kinerja_perusahaan' => '#temuan',
                        'indikator_kinerja_individu' => '13. Tidak ada temuan di audit internal terkait ISO',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                ],
                9 => [
                    [
                        'no' => 1,
                        'indikator_kinerja_perusahaan' => 'Tingkat pemenuhan rekrutmen',
                        'indikator_kinerja_individu' => '1. Tingkat pemenuhan rekrutmen',
                        'baseline_2025' => 0.5,
                        'target_2026' => '100 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 2,
                        'indikator_kinerja_perusahaan' => 'Rerata jam learning per orang',
                        'indikator_kinerja_individu' => '2. Rerata jam pelatihan per orang',
                        'baseline_2025' => 24,
                        'target_2026' => '4 jam/bulan/orang ( Total 48 )',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 3,
                        'indikator_kinerja_perusahaan' => 'Rerata jumlah pendaftar per lowongan',
                        'indikator_kinerja_individu' => '3. Rerata jumlah pendaftar per lowongan',
                        'baseline_2025' => 20,
                        'target_2026' => 20,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 4,
                        'indikator_kinerja_perusahaan' => '#temuan',
                        'indikator_kinerja_individu' => '4. Tidak ada temuan di audit internal terkait ISO',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 7,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '7. Laporan diterbitkan tepat waktu',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 8,
                        'indikator_kinerja_perusahaan' => 'Skor engagement karyawan',
                        'indikator_kinerja_individu' => '8. Skor engagement karyawan',
                        'baseline_2025' => 4,
                        'target_2026' => 3,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 9,
                        'indikator_kinerja_perusahaan' => 'Implementasi ERP',
                        'indikator_kinerja_individu' => '9. Implementasi ERP',
                        'baseline_2025' => 0.8,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                ],
                10 => [
                    [
                        'no' => 1,
                        'indikator_kinerja_perusahaan' => 'K3 UMUM',
                        'indikator_kinerja_individu' => '#temuan',
                        'baseline_2025' => '0 per bulan',
                        'target_2026' => '0 per bulan',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 2,
                        'indikator_kinerja_perusahaan' => null,
                        'indikator_kinerja_individu' => '#temuan',
                        'baseline_2025' => '0 per tahun',
                        'target_2026' => 'N/A',
                        'bobot_target' => null,
                    ],
                ],
                11 => [
                    [
                        'no' => 1,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '1 Tingkat kepuasan pelanggan',
                        'baseline_2025' => 4.5,
                        'target_2026' => '4 dari skala 5',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 2,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '2 Waktu tunggu perbaikan',
                        'baseline_2025' => 3,
                        'target_2026' => 3,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 3,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '3 Jumlah klaim garansi.',
                        'baseline_2025' => 'Belum Ada',
                        'target_2026' => 0.25,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 4,
                        'indikator_kinerja_perusahaan' => 'Gross margin',
                        'indikator_kinerja_individu' => '4. Biaya layanan',
                        'baseline_2025' => 63220870,
                        'target_2026' => 100000000,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 5,
                        'indikator_kinerja_perusahaan' => 'Keluhan pelanggan',
                        'indikator_kinerja_individu' => '5 Tingkat kesalahan perbaikan.',
                        'baseline_2025' => 0,
                        'target_2026' => '0 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 6,
                        'indikator_kinerja_perusahaan' => 'Revenue',
                        'indikator_kinerja_individu' => '6 Jumlah pelanggan yang kembali',
                        'baseline_2025' => 0.6,
                        'target_2026' => 0.8,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 7,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '7 Waktu respons layanan',
                        'baseline_2025' => 24,
                        'target_2026' => 24,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 8,
                        'indikator_kinerja_perusahaan' => 'Penyelesaian PO pelanggan',
                        'indikator_kinerja_individu' => '8 Tingkat penyelesaian PO pelanggan',
                        'baseline_2025' => 1,
                        'target_2026' => '100 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 9,
                        'indikator_kinerja_perusahaan' => 'Implementasi ERP',
                        'indikator_kinerja_individu' => '9 Implementasi ERP',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 10,
                        'indikator_kinerja_perusahaan' => 'Skor Engagement Karyawan',
                        'indikator_kinerja_individu' => '10 Skor Engagement Karyawan',
                        'baseline_2025' => 4,
                        'target_2026' => 3,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 11,
                        'indikator_kinerja_perusahaan' => 'Rerata jam learning per orang',
                        'indikator_kinerja_individu' => '11 Rerata jam pelatihan per orang',
                        'baseline_2025' => 24,
                        'target_2026' => 48,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 12,
                        'indikator_kinerja_perusahaan' => '#temuan',
                        'indikator_kinerja_individu' => '12 Tidak ada temuan di audit internal terkait ISO',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                ],
                12 => [
                    [
                        'no' => 1,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '1 Tingkat kepuasan pelanggan',
                        'baseline_2025' => 4.5,
                        'target_2026' => '4 dari skala 5',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 2,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '2 Waktu tunggu perbaikan',
                        'baseline_2025' => 3,
                        'target_2026' => 3,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 3,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '3 Jumlah klaim garansi.',
                        'baseline_2025' => 'Belum Ada',
                        'target_2026' => 0.25,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 4,
                        'indikator_kinerja_perusahaan' => 'Keluhan pelanggan',
                        'indikator_kinerja_individu' => '4 Tingkat kesalahan perbaikan.',
                        'baseline_2025' => 0,
                        'target_2026' => '0 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 5,
                        'indikator_kinerja_perusahaan' => 'Revenue',
                        'indikator_kinerja_individu' => '5 Jumlah pelanggan yang kembali',
                        'baseline_2025' => 0.6,
                        'target_2026' => 0.8,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 6,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '6 Waktu respons layanan',
                        'baseline_2025' => 24,
                        'target_2026' => 24,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 7,
                        'indikator_kinerja_perusahaan' => 'Penyelesaian PO pelanggan',
                        'indikator_kinerja_individu' => '7 Tingkat penyelesaian PO pelanggan',
                        'baseline_2025' => 1,
                        'target_2026' => '100 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 8,
                        'indikator_kinerja_perusahaan' => 'Implementasi ERP',
                        'indikator_kinerja_individu' => '8 Implementasi ERP',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 9,
                        'indikator_kinerja_perusahaan' => 'Skor Engagement Karyawan',
                        'indikator_kinerja_individu' => '9 Skor Engagement Karyawan',
                        'baseline_2025' => 3.1,
                        'target_2026' => 3,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 10,
                        'indikator_kinerja_perusahaan' => 'Rerata jam learning per orang',
                        'indikator_kinerja_individu' => '10 Rerata jam pelatihan per orang',
                        'baseline_2025' => 24,
                        'target_2026' => 48,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 11,
                        'indikator_kinerja_perusahaan' => '#temuan',
                        'indikator_kinerja_individu' => '11 Tidak ada temuan di audit internal terkait ISO',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                ],
                13 => [
                    [
                        'no' => 1,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '1 Tingkat kepuasan pelanggan',
                        'baseline_2025' => 4.5,
                        'target_2026' => '4 dari skala 5',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 2,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '2 Waktu tunggu perbaikan',
                        'baseline_2025' => 3,
                        'target_2026' => 3,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 3,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '3 Jumlah klaim garansi.',
                        'baseline_2025' => 'Belum Ada',
                        'target_2026' => 0.25,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 4,
                        'indikator_kinerja_perusahaan' => 'Keluhan pelanggan',
                        'indikator_kinerja_individu' => '4 Tingkat kesalahan perbaikan.',
                        'baseline_2025' => 0,
                        'target_2026' => '0 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 5,
                        'indikator_kinerja_perusahaan' => 'Revenue',
                        'indikator_kinerja_individu' => '5 Jumlah pelanggan yang kembali',
                        'baseline_2025' => 0.6,
                        'target_2026' => 0.8,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 6,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '6 Waktu respons layanan',
                        'baseline_2025' => 24,
                        'target_2026' => 24,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 7,
                        'indikator_kinerja_perusahaan' => 'Penyelesaian PO pelanggan',
                        'indikator_kinerja_individu' => '7 Tingkat penyelesaian PO pelanggan',
                        'baseline_2025' => 1,
                        'target_2026' => '100 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 8,
                        'indikator_kinerja_perusahaan' => 'Implementasi ERP',
                        'indikator_kinerja_individu' => '8 Implementasi ERP',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 9,
                        'indikator_kinerja_perusahaan' => 'Skor Engagement Karyawan',
                        'indikator_kinerja_individu' => '9 Skor Engagement Karyawan',
                        'baseline_2025' => 3,
                        'target_2026' => 3,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 10,
                        'indikator_kinerja_perusahaan' => 'Rerata jam learning per orang',
                        'indikator_kinerja_individu' => '10 Rerata jam pelatihan per orang',
                        'baseline_2025' => 24,
                        'target_2026' => 48,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 11,
                        'indikator_kinerja_perusahaan' => '#temuan',
                        'indikator_kinerja_individu' => '11 Tidak ada temuan di audit internal terkait ISO',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                ],
                14 => [
                    [
                        'no' => 1,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '1 Tingkat kepuasan pelanggan',
                        'baseline_2025' => 4.5,
                        'target_2026' => '4 dari skala 5',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 2,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '2 Waktu tunggu perbaikan',
                        'baseline_2025' => 3,
                        'target_2026' => 3,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 3,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '3 Jumlah klaim garansi.',
                        'baseline_2025' => 'Belum Ada',
                        'target_2026' => 0.25,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 4,
                        'indikator_kinerja_perusahaan' => 'Keluhan pelanggan',
                        'indikator_kinerja_individu' => '4 Tingkat kesalahan perbaikan.',
                        'baseline_2025' => 0,
                        'target_2026' => '0 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 5,
                        'indikator_kinerja_perusahaan' => 'Revenue',
                        'indikator_kinerja_individu' => '5 Jumlah pelanggan yang kembali',
                        'baseline_2025' => 0.6,
                        'target_2026' => 0.8,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 6,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '6 Waktu respons layanan',
                        'baseline_2025' => 24,
                        'target_2026' => 24,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 7,
                        'indikator_kinerja_perusahaan' => 'Penyelesaian PO pelanggan',
                        'indikator_kinerja_individu' => '7 Tingkat penyelesaian PO pelanggan',
                        'baseline_2025' => 1,
                        'target_2026' => '100 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 8,
                        'indikator_kinerja_perusahaan' => 'Implementasi ERP',
                        'indikator_kinerja_individu' => '8 Implementasi ERP',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 9,
                        'indikator_kinerja_perusahaan' => 'Skor Engagement Karyawan',
                        'indikator_kinerja_individu' => '9 Skor Engagement Karyawan',
                        'baseline_2025' => 3.8,
                        'target_2026' => 3,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 10,
                        'indikator_kinerja_perusahaan' => 'Rerata jam learning per orang',
                        'indikator_kinerja_individu' => '10 Rerata jam pelatihan per orang',
                        'baseline_2025' => 24,
                        'target_2026' => 48,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 11,
                        'indikator_kinerja_perusahaan' => '#temuan',
                        'indikator_kinerja_individu' => '11 Tidak ada temuan di audit internal terkait ISO',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                ],
                15 => [
                    [
                        'no' => 1,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '1 Tingkat kepuasan pelanggan',
                        'baseline_2025' => 4.5,
                        'target_2026' => '4 dari skala 5',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 2,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '2 Waktu tunggu perbaikan',
                        'baseline_2025' => 3,
                        'target_2026' => 3,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 3,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '3 Jumlah klaim garansi.',
                        'baseline_2025' => 'Belum Ada',
                        'target_2026' => 0.25,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 4,
                        'indikator_kinerja_perusahaan' => 'Keluhan pelanggan',
                        'indikator_kinerja_individu' => '4 Tingkat kesalahan perbaikan.',
                        'baseline_2025' => 0,
                        'target_2026' => '0 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 5,
                        'indikator_kinerja_perusahaan' => 'Revenue',
                        'indikator_kinerja_individu' => '5 Jumlah pelanggan yang kembali',
                        'baseline_2025' => 0.6,
                        'target_2026' => 0.8,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 6,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '6 Waktu respons layanan',
                        'baseline_2025' => 24,
                        'target_2026' => 24,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 7,
                        'indikator_kinerja_perusahaan' => 'Penyelesaian PO pelanggan',
                        'indikator_kinerja_individu' => '7 Tingkat penyelesaian PO pelanggan',
                        'baseline_2025' => 1,
                        'target_2026' => '100 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 8,
                        'indikator_kinerja_perusahaan' => 'Implementasi ERP',
                        'indikator_kinerja_individu' => '8 Implementasi ERP',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 9,
                        'indikator_kinerja_perusahaan' => 'Skor Engagement Karyawan',
                        'indikator_kinerja_individu' => '9 Skor Engagement Karyawan',
                        'baseline_2025' => 3.7,
                        'target_2026' => 3,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 10,
                        'indikator_kinerja_perusahaan' => 'Rerata jam learning per orang',
                        'indikator_kinerja_individu' => '10 Rerata jam pelatihan per orang',
                        'baseline_2025' => 24,
                        'target_2026' => 48,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 11,
                        'indikator_kinerja_perusahaan' => '#temuan',
                        'indikator_kinerja_individu' => '11 Tidak ada temuan di audit internal terkait ISO',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                ],
                16 => [
                    [
                        'no' => 1,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '1 Tingkat kepuasan pelanggan',
                        'baseline_2025' => 4.5,
                        'target_2026' => '4 dari skala 5',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 2,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '2 Waktu tunggu perbaikan',
                        'baseline_2025' => 3,
                        'target_2026' => 3,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 3,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '3 Jumlah klaim garansi.',
                        'baseline_2025' => 'Belum Ada',
                        'target_2026' => 0.25,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 4,
                        'indikator_kinerja_perusahaan' => 'Keluhan pelanggan',
                        'indikator_kinerja_individu' => '4 Tingkat kesalahan perbaikan.',
                        'baseline_2025' => 0,
                        'target_2026' => '0 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 5,
                        'indikator_kinerja_perusahaan' => 'Revenue',
                        'indikator_kinerja_individu' => '5 Jumlah pelanggan yang kembali',
                        'baseline_2025' => 0.6,
                        'target_2026' => 0.8,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 6,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '6 Waktu respons layanan',
                        'baseline_2025' => 24,
                        'target_2026' => 24,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 7,
                        'indikator_kinerja_perusahaan' => 'Penyelesaian PO pelanggan',
                        'indikator_kinerja_individu' => '7 Tingkat penyelesaian PO pelanggan',
                        'baseline_2025' => 1,
                        'target_2026' => '100 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 8,
                        'indikator_kinerja_perusahaan' => 'Implementasi ERP',
                        'indikator_kinerja_individu' => '8 Implementasi ERP',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 9,
                        'indikator_kinerja_perusahaan' => 'Skor Engagement Karyawan',
                        'indikator_kinerja_individu' => '9 Skor Engagement Karyawan',
                        'baseline_2025' => 4,
                        'target_2026' => 3,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 10,
                        'indikator_kinerja_perusahaan' => 'Rerata jam learning per orang',
                        'indikator_kinerja_individu' => '10 Rerata jam pelatihan per orang',
                        'baseline_2025' => 24,
                        'target_2026' => 48,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 11,
                        'indikator_kinerja_perusahaan' => '#temuan',
                        'indikator_kinerja_individu' => '11 Tidak ada temuan di audit internal terkait ISO',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                ],
                17 => [
                    [
                        'no' => 1,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '1 Tingkat kepuasan pelanggan',
                        'baseline_2025' => 4.5,
                        'target_2026' => '4 dari skala 5',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 2,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '2 Waktu tunggu perbaikan',
                        'baseline_2025' => 3,
                        'target_2026' => 3,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 3,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '3 Jumlah klaim garansi.',
                        'baseline_2025' => 'Belum Ada',
                        'target_2026' => 0.25,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 4,
                        'indikator_kinerja_perusahaan' => 'Keluhan pelanggan',
                        'indikator_kinerja_individu' => '4 Tingkat kesalahan perbaikan.',
                        'baseline_2025' => 0,
                        'target_2026' => '0 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 5,
                        'indikator_kinerja_perusahaan' => 'Revenue',
                        'indikator_kinerja_individu' => '5 Jumlah pelanggan yang kembali',
                        'baseline_2025' => 0.6,
                        'target_2026' => 0.8,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 6,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '6 Waktu respons layanan',
                        'baseline_2025' => 24,
                        'target_2026' => 24,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 7,
                        'indikator_kinerja_perusahaan' => 'Penyelesaian PO pelanggan',
                        'indikator_kinerja_individu' => '7 Tingkat penyelesaian PO pelanggan',
                        'baseline_2025' => 1,
                        'target_2026' => '100 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 8,
                        'indikator_kinerja_perusahaan' => 'Implementasi ERP',
                        'indikator_kinerja_individu' => '8 Implementasi ERP',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 9,
                        'indikator_kinerja_perusahaan' => 'Skor Engagement Karyawan',
                        'indikator_kinerja_individu' => '9 Skor Engagement Karyawan',
                        'baseline_2025' => 3.1,
                        'target_2026' => 3,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 10,
                        'indikator_kinerja_perusahaan' => 'Rerata jam learning per orang',
                        'indikator_kinerja_individu' => '10 Rerata jam pelatihan per orang',
                        'baseline_2025' => 24,
                        'target_2026' => 48,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 11,
                        'indikator_kinerja_perusahaan' => '#temuan',
                        'indikator_kinerja_individu' => '11 Tidak ada temuan di audit internal terkait ISO',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                ],
                18 => [
                    [
                        'no' => 1,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '1. Tingkat Insiden Keamanan: Jumlah insiden keamanan per periode',
                        'baseline_2025' => '0 perbulan',
                        'target_2026' => '0 perbulan',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 2,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '2. Waktu Respons terhadap Permintaan: Waktu respons terhadap permintaan',
                        'baseline_2025' => 'Sameday',
                        'target_2026' => 'Sameday',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 3,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '3. Rasio Kepatuhan terhadap Prosedur',
                        'baseline_2025' => '100 %',
                        'target_2026' => '100 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 4,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '4. Jumlah Pelanggaran Keamanan',
                        'baseline_2025' => '0 perbulan',
                        'target_2026' => '0 perbulan',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 5,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '5. Kedisiplinan Petugas : Kepatuhan terhadap peraturan',
                        'baseline_2025' => '4 Skala 5',
                        'target_2026' => '4 Skala 5',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 6,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '6. Keramahan Petugas Keamanan: Perilaku ramah terhadap pelanggan',
                        'baseline_2025' => '4 Skala 5',
                        'target_2026' => '4 Skala 5',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 7,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '7. Kebersihan Fasilitas Keamanan: Kebersihan fasilitas keamanan',
                        'baseline_2025' => '100 %',
                        'target_2026' => '100 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 8,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '8. Pemeriksaan Fasilitas',
                        'baseline_2025' => '100 %',
                        'target_2026' => '100 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 9,
                        'indikator_kinerja_perusahaan' => 'Skor engagement karyawan',
                        'indikator_kinerja_individu' => '9. Skor engagement karyawan',
                        'baseline_2025' => 2.3,
                        'target_2026' => 3,
                        'bobot_target' => null,
                    ],
                ],
                19 => [
                    [
                        'no' => 1,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '1. Tingkat Kepatuhan Waktu: Persentase kedatangan tepat waktu',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 2,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '2. Rasio Kecelakaan: Jumlah kecelakaan per 1.000 km',
                        'baseline_2025' => 0,
                        'target_2026' => 0,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 3,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '3. Konsumsi Bahan Bakar: Rata-rata konsumsi bahan bakar',
                        'baseline_2025' => 0,
                        'target_2026' => '1km/0.14 kwh',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 4,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '4. Kualitas Pelayanan',
                        'baseline_2025' => 4,
                        'target_2026' => '4 skala 5',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 5,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '5. Kedisiplinan : Kepatuhan terhadap peraturan',
                        'baseline_2025' => 4,
                        'target_2026' => '4 skala 5',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 6,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '6. Keramahan : Perilaku ramah terhadap pelanggan',
                        'baseline_2025' => 4,
                        'target_2026' => '4 skala 5',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 7,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '7. Kebersihan Kendaraan',
                        'baseline_2025' => 4,
                        'target_2026' => '4 skala 5',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 8,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '8. Keterampilan Mengemudi',
                        'baseline_2025' => 4,
                        'target_2026' => '4 skala 5',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 9,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '9. Pemeriksaan dan Perawatan Kendaraan',
                        'baseline_2025' => '100 %',
                        'target_2026' => '100 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 10,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '10. Pemeriksaan jatuh tempo STNK',
                        'baseline_2025' => '100 %',
                        'target_2026' => '100 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 11,
                        'indikator_kinerja_perusahaan' => 'Skor engagement karyawan',
                        'indikator_kinerja_individu' => '11. Skor engagement karyawan',
                        'baseline_2025' => 3.7,
                        'target_2026' => 3,
                        'bobot_target' => null,
                    ],
                ],
                20 => [
                    [
                        'no' => 1,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '1. Laporan diterbitkan tepat waktu',
                        'baseline_2025' => 0.85,
                        'target_2026' => '100 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 2,
                        'indikator_kinerja_perusahaan' => 'Implementasi ERP',
                        'indikator_kinerja_individu' => '2. Implementasi ERP',
                        'baseline_2025' => 0.85,
                        'target_2026' => '100 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 3,
                        'indikator_kinerja_perusahaan' => 'Rerata jam learning per orang',
                        'indikator_kinerja_individu' => '3. Rerata jam pelatihan per orang',
                        'baseline_2025' => 24,
                        'target_2026' => '4 jam/bulan/orang ( Total48 )',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 4,
                        'indikator_kinerja_perusahaan' => 'Skor engagement karyawan',
                        'indikator_kinerja_individu' => '4. Skor engagement karyawan',
                        'baseline_2025' => 4,
                        'target_2026' => 3,
                        'bobot_target' => null,
                    ],
                ],
                21 => [
                    [
                        'no' => 1,
                        'indikator_kinerja_perusahaan' => 'Gross margin',
                        'indikator_kinerja_individu' => '1. Tingkat Penghematan Biaya (Cost Savings Rate): Persentase penghematan biaya dibandingkan dengan tahun sebelumnya',
                        'baseline_2025' => 0.02,
                        'target_2026' => 0.1,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 2,
                        'indikator_kinerja_perusahaan' => 'Ketepatan Kedatangan Material',
                        'indikator_kinerja_individu' => '2. Waktu Pengadaan (Lead Time): Waktu antara pemesanan dan penerimaan barang.',
                        'baseline_2025' => 0.75,
                        'target_2026' => 'Maksimum 2 hari kerja',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 3,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '3. Tingkat Ketersediaan Barang (Fill Rate): Persentase barang yang tersedia saat diperlukan',
                        'baseline_2025' => 0.9,
                        'target_2026' => 0.9,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 4,
                        'indikator_kinerja_perusahaan' => 'Ketepatan Kedatangan Material',
                        'indikator_kinerja_individu' => '4. Jumlah Pemesanan yang Tepat Waktu (On-Time Delivery Rate): Persentase pemesanan yang diterima tepat waktu',
                        'baseline_2025' => 0.9,
                        'target_2026' => 0.8,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 5,
                        'indikator_kinerja_perusahaan' => 'Ketepatan Kedatangan Material',
                        'indikator_kinerja_individu' => '5. Kesesuaian Kualitas Barang (Quality Rate): Persentase barang yang memenuhi standar kualitas',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 6,
                        'indikator_kinerja_perusahaan' => 'Ketepatan Pembayaran',
                        'indikator_kinerja_individu' => '6. Kepuasan Supplier (Supplier Satisfaction Rate): Tingkat kepuasan supplier terhadap kerjasama',
                        'baseline_2025' => 'Belum Ada',
                        'target_2026' => '3 skala 5',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 7,
                        'indikator_kinerja_perusahaan' => 'Implementasi ERP',
                        'indikator_kinerja_individu' => '7. Implementasi ERP',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 8,
                        'indikator_kinerja_perusahaan' => 'Skor engagement karyawan',
                        'indikator_kinerja_individu' => '8. Skor engagement karyawan',
                        'baseline_2025' => 3.8,
                        'target_2026' => '3 skala 5',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 9,
                        'indikator_kinerja_perusahaan' => 'Rerata jam learning per orang',
                        'indikator_kinerja_individu' => '9. Rerata jam learning per orang',
                        'baseline_2025' => 24,
                        'target_2026' => '4 jam/bulan/orang ( Total 48 )',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 10,
                        'indikator_kinerja_perusahaan' => '#temuan',
                        'indikator_kinerja_individu' => '10. Tidak ada temuan di audit internal terkait ISO',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                ],
                22 => [
                    [
                        'no' => 1,
                        'indikator_kinerja_perusahaan' => 'Revenue',
                        'indikator_kinerja_individu' => '1.Target penjualan',
                        'baseline_2025' => 'N/A',
                        'target_2026' => 9750000000,
                        'bobot_target' => 0.7,
                    ],
                    [
                        'no' => 2,
                        'indikator_kinerja_perusahaan' => 'Revenue',
                        'indikator_kinerja_individu' => '2. Tingkat konversi penjualan',
                        'baseline_2025' => 'N/A',
                        'target_2026' => 0.8,
                        'bobot_target' => 0.02,
                    ],
                    [
                        'no' => 3,
                        'indikator_kinerja_perusahaan' => '# Pelanggan Baru',
                        'indikator_kinerja_individu' => '3. Jumlah pelanggan baru',
                        'baseline_2025' => 'N/A',
                        'target_2026' => 6,
                        'bobot_target' => 0.0166666666666667,
                    ],
                    [
                        'no' => 4,
                        'indikator_kinerja_perusahaan' => 'Revenue',
                        'indikator_kinerja_individu' => '4. Nilai Kontrak',
                        'baseline_2025' => 'N/A',
                        'target_2026' => 9750000000,
                        'bobot_target' => 0.0166666666666667,
                    ],
                    [
                        'no' => 5,
                        'indikator_kinerja_perusahaan' => 'Revenue',
                        'indikator_kinerja_individu' => '5. Waktu penjualan ( Rata - rata 30 hari kerja )',
                        'baseline_2025' => 'N/A',
                        'target_2026' => 1,
                        'bobot_target' => 0.0166666666666667,
                    ],
                    [
                        'no' => 6,
                        'indikator_kinerja_perusahaan' => 'Indeks survey kepuasan pelanggan',
                        'indikator_kinerja_individu' => '6. Tingkat kepuasan pelanggan',
                        'baseline_2025' => 'N/A',
                        'target_2026' => 4,
                        'bobot_target' => 0.0166666666666667,
                    ],
                    [
                        'no' => 7,
                        'indikator_kinerja_perusahaan' => 'Revenue',
                        'indikator_kinerja_individu' => '7. Retensi pelanggan',
                        'baseline_2025' => 'N/A',
                        'target_2026' => 0.8,
                        'bobot_target' => 0.0166666666666667,
                    ],
                    [
                        'no' => 8,
                        'indikator_kinerja_perusahaan' => 'Product share',
                        'indikator_kinerja_individu' => '8. Product share',
                        'baseline_2025' => 'N/A',
                        'target_2026' => 19,
                        'bobot_target' => 0.05,
                    ],
                    [
                        'no' => 9,
                        'indikator_kinerja_perusahaan' => 'Penyelesaian PO pelanggan',
                        'indikator_kinerja_individu' => '9. Tingkat penyelesaian PO pelanggan',
                        'baseline_2025' => 'N/A',
                        'target_2026' => 1,
                        'bobot_target' => 0.08,
                    ],
                    [
                        'no' => 10,
                        'indikator_kinerja_perusahaan' => 'Implementasi ERP',
                        'indikator_kinerja_individu' => '10. Implementasi ERP',
                        'baseline_2025' => 'N/A',
                        'target_2026' => 1,
                        'bobot_target' => 0.0166666666666667,
                    ],
                    [
                        'no' => 11,
                        'indikator_kinerja_perusahaan' => 'Skor Engagement Karyawan',
                        'indikator_kinerja_individu' => '11. Skor Engagement Karyawan',
                        'baseline_2025' => 'N/A',
                        'target_2026' => 3,
                        'bobot_target' => 0.0166666666666667,
                    ],
                    [
                        'no' => 12,
                        'indikator_kinerja_perusahaan' => 'Rerata jam learning per orang',
                        'indikator_kinerja_individu' => '12. Rerata jam pelatihan per orang',
                        'baseline_2025' => 'N/A',
                        'target_2026' => 48,
                        'bobot_target' => 0.0166666666666667,
                    ],
                    [
                        'no' => 13,
                        'indikator_kinerja_perusahaan' => '#temuan',
                        'indikator_kinerja_individu' => '13. Tidak ada temuan di audit interna dan eksternal terkait ISO',
                        'baseline_2025' => 'N/A',
                        'target_2026' => 1,
                        'bobot_target' => 0.0166666666666667,
                    ],
                ],
                25 => [
                    [
                        'no' => 1,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '1. Tingkat Kepatuhan Waktu: Persentase kedatangan tepat waktu',
                        'baseline_2025' => 1,
                        'target_2026' => 1,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 2,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '2. Rasio Kecelakaan: Jumlah kecelakaan per 1.000 km',
                        'baseline_2025' => 0,
                        'target_2026' => 0,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 3,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '3. Konsumsi Bahan Bakar: Rata-rata konsumsi bahan bakar',
                        'baseline_2025' => '11 Km / Liter',
                        'target_2026' => null,
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 4,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '4. Kualitas Pelayanan',
                        'baseline_2025' => 4,
                        'target_2026' => '4 skala 5',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 5,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '5. Kedisiplinan : Kepatuhan terhadap peraturan',
                        'baseline_2025' => 4,
                        'target_2026' => '4 skala 5',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 6,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '6. Keramahan : Perilaku ramah terhadap pelanggan',
                        'baseline_2025' => 4,
                        'target_2026' => '4 skala 5',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 7,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '7. Kebersihan Kendaraan',
                        'baseline_2025' => 4,
                        'target_2026' => '4 skala 5',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 8,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '8. Keterampilan Mengemudi',
                        'baseline_2025' => 4,
                        'target_2026' => '4 skala 5',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 9,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '9. Pemeriksaan dan Perawatan Kendaraan',
                        'baseline_2025' => '100 %',
                        'target_2026' => '100 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 10,
                        'indikator_kinerja_perusahaan' => 'Kualitas kerja berdasarkan SOP',
                        'indikator_kinerja_individu' => '10. Pemeriksaan jatuh tempo STNK',
                        'baseline_2025' => '100 %',
                        'target_2026' => '100 %',
                        'bobot_target' => null,
                    ],
                    [
                        'no' => 11,
                        'indikator_kinerja_perusahaan' => 'Skor engagement karyawan',
                        'indikator_kinerja_individu' => '11. Skor engagement karyawan',
                        'baseline_2025' => 3.8,
                        'target_2026' => 3,
                        'bobot_target' => null,
                    ],
                ],
            ];

            foreach ($data as $goalId => $kpis) {
                foreach ($kpis as $kpi) {
                    GoalKpi::create(array_merge(
                        ['goal_id' => $goalId],
                        $kpi
                    ));
                }
            }
        });
    }
}